### PR TITLE
Retry failed artifact downloads

### LINKED ISSUE #102: Occasional failure to download artifact from job dependency
A job will occasionally fail to get the artifact from a dependency job, printing:

```
> submit lava/testjob.yaml
Failed to get artifact from generate-tests
lava/testjob.yaml not found in artifacts
```

As seen in: https://gitlab.collabora.com/nfraprado/linux/-/jobs/491582

Even though an [earlier](https://gitlab.collabora.com/nfraprado/linux/-/jobs/491581) and [later](https://gitlab.collabora.com/nfraprado/linux/-/jobs/491583) jobs with the same dependency succeed, and [the very same job when retried](https://gitlab.collabora.com/nfraprado/linux/-/jobs/491652) also succeeds.

The current error message doesn't give enough details about what went wrong though.

### PR DESCRIPTION
**Pull request by refi64**
Right now, if downloading an artifact fails due to, say, network or server errors, the runner crate simply returns an error. This isn't ideal, since *some* errors will inevitably occur; even the official runner implementation has retries for artifact downloads.

This adds a simple retry system on top of downloads: if a "retriable" error occurs (namely, reqwest-level error or a 5xx status code), then the download will be repeatedly retried up to 10 times.

In order to be able to test the change, this adds a new method to the mock API, `set_inject_artifact_download_failures`, which will cause N artifact downloads to fail before one can succeed.

Fixes: collabora/lava-gitlab-runner#102

### CODE REVIEW

File: gitlab-runner/src/job.rs [hunk 1]
```diff
@@ -63,6 +69,14 @@ pub struct Dependency<'a> {
     dependency: &'a JobDependency,
 }
 
+fn is_retriable_error(err: &ClientError) -> bool {
```
Comment (sjoerdsimons) [inline gitlab-runner/src/job.rs:72]: Should this be directly on `Error`

File: gitlab-runner/src/job.rs [hunk 2]
```diff
@@ -91,6 +105,35 @@ impl Dependency<'_> {
         self.dependency.artifacts_file.as_ref().map(|a| a.size)
     }
 
+    async fn download_impl(
+        &self,
+        writer: Arc<AsyncMutex<impl AsyncWrite + Unpin>>,
+    ) -> Result<(), ClientError> {
+        let strategy = FibonacciBackoff::from_millis(100).map(jitter).take(10);
```
Comment (sjoerdsimons) [inline gitlab-runner/src/job.rs:112]: 100ms seems aggressive; 10 times without jitter is:
```
=> 100ms
=> 100ms
=> 200ms
=> 300ms
=> 500ms
=> 800ms
=> 1.3s
=> 2.1s
=> 3.4s
=> 5.5s
Total: 14.3s
```

starting from 500 would be:
```
> 500ms
=> 500ms
=> 1s
=> 1.5s
=> 2.5s
=> 4s
=> 6.5s
=> 10.5s
=> 17s
=> 27.5s
Total: 71.5s
```

Ofcourse this is a bit finger in the air as there is no way to know what he remote issue is; But a less aggressive retry might probably be better

File: gitlab-runner/src/job.rs (hunk 1 above)
Comment (refi64) [reply gitlab-runner/src/job.rs:72]: Maaaybe in the future? But right now this logic is pretty specific to artifact downloads, so we might have a slightly different standard for "retriable" elsewhere.

**Comment by sjoerdsimons** [comment]
@refi64 pushed a commit on top to get rid of the arc mutex wrapping. Could you give me your opinion on it ?

**Review by sjoerdsimons — DISMISSED** [review]

File: gitlab-runner/src/job.rs [hunk 3]
```diff
@@ -105,33 +102,29 @@ impl Dependency<'_> {
...
+    {
+        let mut strategy = FibonacciBackoff::from_millis(900).map(jitter).take(4);
+        loop {
+            let r = self
+                .job
+                .client
+                .download_artifact(self.dependency.id, &self.dependency.token, &mut writer)
+                .await;
+
+            match (r, strategy.next()) {
```
Comment (refi64) [inline gitlab-runner/src/job.rs:117]: oh this is really quite slick, I hadn't considered that we could just *iterate over the strategy ourselves* by nature of it being an iterable, I guess I had the other dead-ish backoff library I used in obs-gitlab-runner stuck in my head. (might also move that over at some point, because the use of closures has—again—caused my an incredible amount of lifetime headaches.)

**Comment by refi64** [comment]
conflicts resolved
